services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  user_service:
    build: ./user_auth_service
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/user_db
      - JWT_SECRET_KEY=your_secret_key
    ports:
      - "5001:5001"

  product_service:
    build: ./product_inventory_service
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/product_db
      - JWT_SECRET_KEY=your_secret_key
      - REDIS_HOST=redis
    ports:
      - "5002:5002"

  order_service:
    build: ./order_payment_service
    depends_on:
      - postgres
      - product_service
      - notification_service
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/order_db
      - JWT_SECRET_KEY=your_secret_key
      - PRODUCT_SERVICE_URL=http://product_service:5002
      - NOTIFICATION_SERVICE_URL=http://notification_service:5004
    ports:
      - "5003:5003"

  notification_service:
    build: ./notification_service
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/notification_db
      - JWT_SECRET_KEY=your_secret_key
      - SMTP_USERNAME=your-email@gmail.com
      - SMTP_PASSWORD=your-password
    ports:
      - "5004:5004"

  api_gateway:
    build: ./api_gateway
    depends_on:
      - user_service
      - product_service
      - order_service
      - notification_service
    environment:
      - USER_SERVICE_URL=http://user_service:5001
      - PRODUCT_SERVICE_URL=http://product_service:5002
      - ORDER_SERVICE_URL=http://order_service:5003
      - NOTIFICATION_SERVICE_URL=http://notification_service:5004
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - api_gateway